language: node_js
node_js:
  - 'node'
cache:
  directories:
    - 'node_modules' # This will tell Travis CI to cache the dependencies
before_script:
  - npm prune
script:
  - npm test
  - npm run test:coverage
  - npm run build
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: now --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script:
      - now --token $NOW_TOKEN
      - git config user.email "travis@travis.org"
      - git config user.name "Travis CI"
      - npm run release # standard-version, with [skip ci] to prevent infinite loop
      - git remote rm origin
      - git remote add origin https://${GITHUB_API_USER}:${GITHUB_API_KEY}@${GITHUB_REPO_REF}
      - git push --follow-tags origin master
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --token $NOW_TOKEN &&
      npm run release &&
      git push --follow-tags origin master
    skip_cleanup: true
    on:
      master: true
