language: node_js
node_js:
  - 'node'
cache:
  directories:
    - 'node_modules' # This will tell Travis CI to cache the dependencies
notifications:
  slack: pieriandx:OGWHyqqjgCDbx3OJLFaV8syQ
before_script:
  - npm prune
script:
  - npm test
  - npm run test:coverage
  - npm run build
before_deploy:
  - npm install now --no-save # Install Now CLI on Travis
deploy:
  # Deploys for feature/fix branches
  - provider: script
      script: now --token $NOW_TOKEN -A now.ci.json --team pieriandx
      skip_cleanup: true
      on:
        all_branches: true
        condition: NOT branch =~ /^(development|master)$/
  # Deploys for development (app-dev.pieriandx.xyz)
  - provider: script # Run a custom deployment script which we will define below
    script: now --token $NOW_TOKEN -A now.ci.json --team pieriandx &&
      now alias --token $NOW_TOKEN --team pieriandx app-dev.pieriandx.xyz
    skip_cleanup: true
    on:
      branch: development
  # Deploys for production (master) (app.pieriandx.xyz)
  - provider: script
    script: now --token $NOW_TOKEN -A now.ci.json --team pieriandx &&
      now alias --token $NOW_TOKEN --team pieriandx app.pieriandx.xyz &&
      git config --global user.email "build@travis-ci.org" &&
      git config --global user.name "Travis CI" &&
      git checkout $TRAVIS_BRANCH &&
      git remote rm origin &&
      git remote add origin https://${GITHUB_API_USER}:${GITHUB_API_KEY}@${GITHUB_REPO_REF} &&
      npm run release &&
      git commit --amend -m " [skip ci]" &&
      git push --follow-tags origin $TRAVIS_BRANCH &&
      git push origin $TRAVIS_BRANCH --tags
    skip_cleanup: true
    on:
      branch: master
      condition: -z $(git tag --points-at $TRAVIS_COMMIT)
