language: node_js
node_js:
  - 'node'
cache:
  directories:
    - 'node_modules' # This will tell Travis CI to cache the dependencies
before_script:
  - npm prune
script:
  - npm test
  - npm run test:coverage
  - npm run build
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: now --token $NOW_TOKEN --team pieriandx &&
      now alias --token $NOW_TOKEN --team pieriandx app-dev.pieriandx.xyz
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --token $NOW_TOKEN --team pieriandx &&
      now alias --token $NOW_TOKEN --team pieriandx app.pieriandx.xyz &&
      git config --global user.email "travis@travis.org" &&
      git config --global user.name "Travis CI" &&
      git remote rm origin &&
      git remote add origin https://${GITHUB_API_USER}:${GITHUB_API_KEY}@${GITHUB_REPO_REF} &&
      npm run release &&
      git push --follow-tags origin master
    skip_cleanup: true
    on:
      branch: master
