language: node_js
node_js:
  - '11.10.1'
cache:
  directories:
    - 'node_modules' # This will tell Travis CI to cache the dependencies
notifications:
  slack: pieriandx:OGWHyqqjgCDbx3OJLFaV8syQ
before_script:
  - npm prune
script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - npm test
  - npm run test:coverage
  - npm run build
before_deploy:
  - npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script
    script: now --token $NOW_TOKEN -A now.ci.json --team pieriandx &&
      now alias --token $NOW_TOKEN --team pieriandx app-dev.pieriandx.xyz
    skip_cleanup: true
    on:
      branch: development
  - provider: script
    script: now --token $NOW_TOKEN -A now.ci.json --team pieriandx &&
      now alias --token $NOW_TOKEN --team pieriandx app.pieriandx.xyz &&
      git config --global user.email "build@travis-ci.org" &&
      git config --global user.name "Travis CI" &&
      git checkout $BRANCH &&
      git remote rm origin &&
      git remote add origin https://${GITHUB_API_USER}:${GITHUB_API_KEY}@${GITHUB_REPO_REF} &&
      npm run release &&
      git push --follow-tags origin $BRANCH &&
      git push origin $BRANCH --tags &&
      git fetch origin development &&
      git checkout development &&
      git merge --no-ff master &&
      git push origin development
    skip_cleanup: true
    on:
      branch: master
